### ISSUE TITLE
Project using TinyUSB installed with windows installer only shows code :10 

### ISSUE THREAD

**Issue by NicoAICP** [raspberrypi/pico-setup-windows#13]
I tried to compile my project PTPE with branch sdk15 with the windows installer for pi pico development. [https://github.com/NicoAICP/PTPE/tree/sdk15](url)
The uf2 compiles just fine, but after plugging it into my pc and selecting skylanders, it throws the issue that the device couldnt be started (code 10).
If i compile the project using linux, same sdk version and everything, I do not get the error code 10 and it boots up just fine.

Could you guys take a look, if this is an issue with the windows installer?
You probably wont be able to run my code due to it needing hardware for the pi pico, but it should work the same if you just create a tinyusb project acting as a hid device.

**Comment by lurch** [comment]
ping @hathach in case he has any ideas.
