### ISSUE TITLE
add ability to specify what need to install.

### ISSUE THREAD

**Issue by slyshykO** [raspberrypi/pico-setup-windows#14]
As a developer, I have installed VScode, Cmake, Ninja, Pyhton and arm-none-eabi-gcc.

I don't need it will be installed twice.

It would be handy if I could install only tools specific to rp2040.

**Comment by lurch** [comment]
If you've already got most of the necessary tools installed, perhaps you'd be better served by Section 9.2 of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf ?

**Comment by ndabas** [comment]
We don't really support partial installs currently, but if you have most of the tools already and just need the additional pre-compiled tools, you can open the installer exe file using 7-zip and just extract what you want. Just be aware that using the tools that way isn't a supported or documented scenario.

**Comment by buldo** [comment]
Original "Pico setup for Windows" suppports partial installs. This is very useful to get `pico-env.cmd` and other tools like project creator.

For example - I'm .NET developer. I always have VisualStudio(with build tools) and Visual Studio Code installed on my PC. So I was happy to install everything "not installed" but needed to work

**Comment by ndabas** [comment]
You can build the original "Pico setup for Windows" installer yourself if you follow the instructions in the root ReadMe and use this command to build the installer:
```
.\build.ps1 .\config\x64.json -SkipSigning -Compression zlib
```

However the reason why we don't support this method of installation anymore is that you might end up with missing or incompatible components, and we wanted something that will (almost) always work, irrespective of what you have installed on your system already.

**Comment by ndabas** [comment]
Closing because no further action is needed.
