### ISSUE TITLE
Compiler 'arm-none-eabi-gcc' not found

### ISSUE THREAD

**Issue by philwu** [raspberrypi/pico-setup-windows#15]
Hi, friends.

I  have download and run [Windows Pico Installer](https://github.com/raspberrypi/pico-setup-windows).

But I got following error when I tried to make the pico-examples folder:

`Compiler 'arm-none-eabi-gcc' not found`

What should I do? Add a "PICO_TOOLCHAIN_PATH" env variable? What value should be?

I am using Windows 11 22H2 22621.1555

![1682487121586](https://user-images.githubusercontent.com/5704024/234478526-1e438444-8d85-4b58-bd4d-32028dfc0cda.png)

**Comment by ghollingworth** [comment]
It looks like it’s using the Microsoft visual studio version of cmake…

**Comment by philwu** [comment]
> 

That's right. I use cmake from pico sdk and problem is gone. Thank you very much.

**Comment by Vodlex1** [comment]
> > 
> 
> That's right. I use cmake from pico sdk and problem is gone. Thank you very much.

Hello, I'm facing the exact same issue and I just wanted to ask how you switched over to the pico sdk cmake?
Thanks.

**Comment by ndabas** [comment]
> Hello, I'm facing the exact same issue and I just wanted to ask how you switched over to the pico sdk cmake?

Just make sure you launch VS Code or the command prompt using the "Pico - ..." shortcuts.

**Comment by Mola19** [comment]
No idea if i overread that add some point or not, but apparently this issue appears if you don't restart after installing.
