### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by mohdrais** [raspberrypi/pico-setup-windows#19]
How to overcome the missing components as shpwn in the Pico-Developer Command Pr
![ScreenshotPico](https://github.com/raspberrypi/pico-setup-windows/assets/63096939/fd6a7785-c03b-428f-8d7d-75924d07f0a6)
ompt

**Comment by ndabas** [comment]
This should really not happen after a successful install -- are all of the tools present and installed into `C:\Program Files\Raspberry Pi\Pico SDK v1.5.0`? You should have folders like `cmake`, `python`, `gcc-arm-none-eabi`, and so on for all of the tools.

Additionally, I see the screenshot is from Windows Terminal, does starting the Pico - Developer Command Prompt from the Start menu work?

**Comment by mohdrais** [comment]
Yes, all the folders mentioned (eg cmake, python etc) are installed. Pico-Developer Command Prompt does  work as shown in the picture previously
![ScreenshotB](https://github.com/raspberrypi/pico-setup-windows/assets/63096939/76dc1ce9-5f62-4a43-a908-fa8fff7b9f2f)
but Pico- DeveloperShell does not work
