### ISSUE TITLE
Pico - Visual Studio Code link does nothing if VS code is not in PATH

### ISSUE THREAD

**Issue by wattyka** [raspberrypi/pico-setup-windows#26]
If VS Code was installed with "add to PATH environment variable"  not checked in the VS Code Setup, the "Pico - Visual Studio Code" link seems to do nothing (no error message etc.). 

The pico-setup and/or the pico-code.ps1 should probably check if VS Code is actually available in the path and give some meaningful feedback if it is not.

**Comment by ndabas** [comment]
Yes, agreed, the launch script should provide meaningful feedback if it fails, and it would fail in the scenario described.

**Comment by patric-r** [comment]
Same issue here. This should documented at least
