### ISSUE TITLE
Installer not working on Windows 11 on Arm64

### ISSUE THREAD

**Issue by Nabla128k** [raspberrypi/pico-setup-windows#34]
Installer refuse to work on Arm64 Windows 11. Is there a reason for this?

**Comment by ndabas** [comment]
Yes. We haven't validated that the toolchain (which is all built for x64) works correctly under emulation.

**Comment by Nabla128k** [comment]
Toolchain itself works well if manually installed. But not the installer.

**Comment by gbaman** [comment]
Just following up on this, any luck at removing the limitation for Arm64 version of windows?

**Comment by ebadger** [comment]
+1 for a native ARM64 tool chain

**Comment by ndabas** [comment]
This will be done in the next release of the installer -- which will coincide with the next release of the Pico SDK.

Note that there is no fully native ARM64 toolchain, as we include the ARM GCC and other tools from various vendors, and many do not have native ARM64 releases. We will include the tools that do have ARM64 releases, though.
