### ISSUE TITLE
No suitable code signing certificates found

### ISSUE THREAD

**Issue by chgenly** [raspberrypi/pico-setup-windows#37]
Running setup on windows 10 I get the following failure.

![image](https://github.com/raspberrypi/pico-setup-windows/assets/484383/5ad5273f-2e42-419d-9c6e-e19151227b34)

**Comment by ndabas** [comment]
[As noted in the ReadMe](https://github.com/raspberrypi/pico-setup-windows#pico-setup-for-windows), if you just want to install the tools, download the installer.

The build.ps1 file is for building the installer itself. If that is what you are trying to do, you can add the `-SkipSigning` argument.

**Comment by chgenly** [comment]
Really closed

**Comment by lurch** [comment]
@ndabas I wonder if moving the "Building" part of the Readme to a separate markdown file, might prevent other users from making a similar mistake?

**Comment by ndabas** [comment]
@lurch Agreed, I think we can split that out to a separate file for developers.
