### ISSUE TITLE
Changing from debug to build and run for a Pico W

### ISSUE THREAD

**Issue by XeYaRiQu** [raspberrypi/pico-setup-windows#39]
Hi, not sure if this is the right place to ask this.

I very much appreciate this automated installer for C development on Windows for the Pico boards, but I'd like simply cmake my own project code and run the command to build the executables with the uf2 binaries without debugging if that makes sense. How should I go about doing that? What settings do I change and where?

Thanks in advance

**Comment by ndabas** [comment]
If you just want to build your code without debugging:
- From Visual Studio Code, [follow the steps in the tutorial](https://github.com/raspberrypi/pico-setup-windows/blob/master/docs/tutorial.md#building-an-example).
- From the command line, use the commands in the [getting started guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) in a _Pico - Developer Command Prompt_.

**Comment by ndabas** [comment]
It looks like CMake is trying to use NMake Makefiles -- our toolchain is setup for Ninja instead. This should have been configured in your [`.vscode/settings.json`](https://github.com/raspberrypi/pico-setup-windows/blob/master/packages/pico-examples/ide/vscode/settings.json) -- is `cmake.generator` set to `Ninja`?

**Comment by XeYaRiQu** [comment]
Ah, I had set the generator to use `Nmake Makefile` as I was following the getting started guide.

I've changed removed that and it defaults to using Ninja now. Another question: I have set `cmake.buildToolArgs` to `-DPICO_BOARD=pico_w` in `.vscode/settings.json`. Is this correct? Are there other settings that I have to change for the Pico W board?

Right now when starting up Pico - Visual Studio Code, the logs show this:
```
[cmake] Build type is Release
[cmake] PICO target board is pico.
[cmake] Using board configuration from S:/Pico SDK/pico-sdk/src/boards/include/boards/pico.h
```

Again, my sincere thanks for your assistance!

**Comment by ndabas** [comment]
Sure, happy to help!

There is info on changing the board [in the wiki](https://github.com/raspberrypi/pico-setup-windows/wiki/FAQ#how-do-i-set-the-pico_board).

**Comment by XeYaRiQu** [comment]
Got it working, thank you very much!

Cheers!

**Comment by XeYaRiQu** [comment]
Hi! Apologies for reviving this thread, I'm not sure if I should be creating a new one since I'm encountering a different issue but I didn't want to unnecessarily flood the issues page with my questions.

I've got several includes whose source files cannot be opened, while others can:
```
#include "pico/stdlib.h"
#include "pico/binary_info.h"
#include "hardware/timer.h"
#include "hardware/i2c.h" // Cannot open source file
#include "hardware/pwm.h" // Cannot open source file
#include "cyw43_arch.h" // Cannot open source file
```
The errors seem to be due to this:
`#include errors detected based on information provided by the configurationProvider setting. Squiggles are disabled for this translation unit (D:\workspace\myproject\test\main.c).`

Opening only the pico-examples in a separate window, none of these errors appear. I've checked my settings in `workspace/.vscode` and they match those in `workspace/pico-examples/.vscode`.

**Comment by ndabas** [comment]
Did you add the dependencies in your CMakeLists.txt? For example:

```
target_link_libraries(my_project pico_stdlib hardware_i2c hardware_pwm pico_cyw43_arch_none)
```

The last include should probably be `#include "pico/cyw43_arch.h"`.

**Comment by XeYaRiQu** [comment]
Ah, so cmake was the issue! I was thinking it was because of intellisense...

Is `hardware/timer` under stdlib? It wasn't in the cmakelist but didn't get flagged like the others.

**Comment by ndabas** [comment]
Yes, I believe `hardware/timer` is in stdlib. I usually just search the pico-examples repo for whatever library/include I need, and there's usually a minimal example which will show what you need to add to your CMakeLists.txt.

**Comment by XeYaRiQu** [comment]
Got it, thanks again!
