### ISSUE TITLE
Add local Visual Studio Code just like other included software  

### ISSUE THREAD

**Issue by vbolshakov** [raspberrypi/pico-setup-windows#41]
Include VSCode in the installer (may be an option).
Add the "data" folder to VSCode so that the extensions will also be installed locally.
And provide a "portable" version of pico-setup in .zip format without any installation.

**Comment by ndabas** [comment]
Visual Studio Code is updated very frequently, and adding a copy of it to our installer would mean that for most of the lifetime of the installer, users would get an outdated version.

**Comment by lurch** [comment]
The VS Code [licensing terms](https://code.visualstudio.com/license) also don't allow redistribution anyway. More info in https://github.com/microsoft/vscode/issues/60205#issuecomment-1018985581

**Comment by lurch** [comment]
@ndabas If VSCode **isn't** included in the pico-setup-windows installer, why is it listed in https://github.com/raspberrypi/pico-setup-windows/blob/master/README.md#included-software ?

**Comment by lurch** [comment]
Ahh, looking at https://github.com/raspberrypi/pico-setup-windows/blob/master/packages/pico-setup-windows/VSCodeUtils.nsh it seems that pico-setup-windows automatically downloads and installs the latest VSCode installer during setup.

**Comment by ndabas** [comment]
Yes, it is downloaded and installed when the setup is run, but is not 'included' in the sense of the binary being a part of the installer.

I assumed from the phrasing of the issue that the poster was talking about an offline version, because the installer does 'include' VS Code in terms of what it installs.

**Comment by vbolshakov** [comment]
Yes, why not download and unzip VS Code inside SDK.

**Comment by ndabas** [comment]
> Yes, why not download and unzip VS Code inside SDK.

That's already been answered in this thread.
