### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by jpitz31** [raspberrypi/pico-setup-windows#42]
Hello all,  I installed the pico sdk as indicated in the pico-setup-windows git,  set the environment variables, PICO_SDK_PATH and
PICO_EXAMPLES_PATH,  I can cmake and build all of the example programs just fine.

I followed your example for creating a new project from the [pico-setup-windows](https://github.com/raspberrypi/pico-setup-windows/tree/master)/[docs](https://github.com/raspberrypi/pico-setup-windows/tree/master/docs)
/tutorial.md

I created the CmakeLists.txt files as indicated in this tutorial.

When I attempt to make my new project I get the following error:
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at src/CMakeLists.txt:12 (pico_add_extra_outputs):
[cmake]   Unknown CMake command "pico_add_extra_outputs".

I must be missing a path or something.

Please let me know what the resolution is to this issue.

Cheers

Joe

**Comment by ndabas** [comment]
Please see [my response](https://github.com/raspberrypi/pico-setup-windows/issues/43#issuecomment-2104187946) on the other issue, the troubleshotting steps are identical.
