### ISSUE TITLE
Another cmake issue

### ISSUE THREAD

**Issue by jpitz31** [raspberrypi/pico-setup-windows#43]
In following the tutorial on coping all of the files and creating the make files.  When I make the new project
I get all of the below cmake errors.

When I cmake and built the example project, everything worked just fine.

Now I create a new project, with no files I get the below cmake errors:

[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_CXX_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_CXX_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_ASM_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_CXX_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_C_COMPILE_OBJECT
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_LIBRARY_PATH_FLAG
[cmake] CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
[cmake] Missing variable is:
[cmake] CMAKE_LIBRARY_PATH_TERMINATOR

Could you please give some insight on why I am getting this issue?

Cheers

Joe

**Comment by ndabas** [comment]
Since you say that you can build the example project(s) just fine, it is unlikely to be an issue with the Windows installer itself.

I would suggest that you:
- Follow the troubleshooting steps [here](https://github.com/raspberrypi/pico-setup-windows/wiki/Problems-using-Visual-Studio-Code-with-Raspberry-Pi-Pico).
- Post on [the forum](https://forums.raspberrypi.com/viewforum.php?f=144) with more info.
- Or, please provide more info on how you are triggering this build -- command line? VS Code? What exactly is the command line or button/menu option you are using? Did you launch VS Code or the command prompt from the provided shortcuts? Can you also post the contents of your CMakeLists.txt?
