### ISSUE TITLE
No support for SDK 2.0

### ISSUE THREAD

**Issue by BenZonneveld** [raspberrypi/pico-setup-windows#48]
There is no support for the new SDK and the Pico 2 at this moment.
Will there be an update for the pico-setup-windows?

**Comment by ghollingworth** [comment]
We are not intending to support the pico-setup-windows installer in future.  We're instead recommending people use the Visual Studio Code Extension.

https://marketplace.visualstudio.com/items?itemName=raspberry-pi.raspberry-pi-pico

This has been developed to better integrate across all platforms (MacOS, Linux and Windows).
