### ISSUE TITLE
Add adapter speed declaration to the manual openocd invocation command

### ISSUE THREAD

**Issue by P33M** [raspberrypi/pico-setup-windows#6]
https://github.com/raspberrypi/pico-setup-windows/blob/53c1a0df5dc48fc8b5c2e05cad1f68e6b15dcae3/packages/pico-setup-windows/ReadMe.txt#L38 - this needs to include `-c "adapter speed 1000"` to align with the launch.json file.

**Comment by lurch** [comment]
@P33M Should this be 5000 to match the speed we're suggesting in other places?

**Comment by aallan** [comment]
It probably should?

**Comment by ndabas** [comment]
Should be, yes -- let me know and I can update it in these files:
- docs/tutorial.md
- packages/pico-examples/ide/vscode/tasks.json
- packages/pico-examples/ide/vscode/launch.json

**Comment by ghollingworth** [comment]
Checked with Jonathan, and yes this should be 5000

**Comment by ndabas** [comment]
Done in fbcb752a6053cf31c214f0bf4be9d3aa014d4310.
